version: "3.8"

networks:
  microservices-net:
    driver: bridge

services:

  service-registry:
    image: service-registry:1.0.0
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=uat
    networks:
      - microservices-net
    restart: unless-stopped

  config-server:
    image: config-server:1.0.0
    container_name: config-server
    ports:
      - "8087:8087"
    environment:
      - SPRING_PROFILES_ACTIVE=uat
    depends_on:
      - service-registry
    networks:
      - microservices-net
    restart: unless-stopped

  quiz-service:
    image: quiz-service:1.0.0
    container_name: quiz-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=uat
    depends_on:
      - service-registry
      - config-server
    networks:
      - microservices-net
    restart: unless-stopped

  question-service:
    image: question-service:1.0.0
    container_name: question-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=uat
    depends_on:
      - service-registry
      - config-server
    networks:
      - microservices-net
    restart: unless-stopped

  api-gateway:
    image: api-gateway:1.0.0
    container_name: api-gateway
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=uat
    depends_on:
      - service-registry
      - config-server
      - quiz-service
      - question-service
    networks:
      - microservices-net
    restart: unless-stopped
