server:
  port: 9090


spring:
  config:
    import: "optional:configserver:http://config-server:8087"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
            http://localhost:8080/realms/master

  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka

