server:
  port: 8081

spring:
  application:
    name: QUIZ-SERVICE

management:
  endpoints:
    web:
      exposure:
        include: health,info




resilience4j:
  ratelimiter:
    instances:
      quizServiceLimiter:
        limit-for-period: 2
        limit-refresh-period: 4s
        timeout-duration: 0s

eureka:
  instance:
    prefer-ip-address: true